### ISSUE TITLE
ANCHOR_TAB_STRING_NOT_FOUND

### ISSUE THREAD

**Issue by albatross666** [docusign/sample-app-mymedicalrecords-java#6]
https://[mymedicalrecords.sampleapps.docusign.com/financialforms](https://mymedicalrecords.sampleapps.docusign.com/financialforms)

Oops, we have encountered a problem.

Message: Error while requesting server, received a non successful HTTP code 400 with response Body: '{"errorCode":"ANCHOR_TAB_STRING_NOT_FOUND","message":"The specified Anchor Tab string was not found in the document. Anchor Tab String \"*nm2*\" not found."}'

Dump: [Ljava.lang.StackTraceElement;@7d985a91

Please check your account configuration. If you are unable to resolve the problem, [open a new issue on GitHub](https://github.com/docusign/sample-app-mymedicalrecords-java/issues/new).

[Continue](https://mymedicalrecords.sampleapps.docusign.com/)

**Comment by InbarGazit** [comment]
This error means that the string "nm2" was not found in the document in the envelope. I don't know what you're doing exactly, but the way anchor strings work is that DocuSign searches your document for a specific string to place tabs. You need to confirm you have the string, correct string, in the code and the document.

**Comment by albatross666** [comment]
If you fill in an email and a name on your site https://[mymedicalrecords.sampleapps.docusign.com/financialforms](https://mymedicalrecords.sampleapps.docusign.com/financialforms), you get that error.

**Comment by InbarGazit** [comment]
Sorry, this was just fixed by updating the code
