### ISSUE TITLE
ANCHOR_TAB_STRING_NOT_FOUND?

### ISSUE THREAD

**Issue by William-Sheehan** [docusign/sample-app-mymedicalrecords-java#8]
Trying to evaluate Docusign, (vs other esignature solutions). Attempting to use this demo. Entered email and name. Got this message

> Oops, we have encountered a problem.
> 
> Message: Error while requesting server, received a non successful HTTP code 400 with response Body: '{"errorCode":"ANCHOR_TAB_STRING_NOT_FOUND","message":"The specified Anchor Tab string was not found in the document. Anchor Tab String \"*nm2*\" not found."}'
> 
> Dump: [Ljava.lang.StackTraceElement;@33f3a7cd

**Comment by InbarGazit** [comment]
This error indicates the string "nm2" is not found on the document that was sent to DocuSign, which document was it? do you have it? it should include this string somewhere or you can update the code from "nm2" to a string that does show in the document

**Comment by InbarGazit** [comment]
Sorry, this was just fixed by updating the code
